### ISSUE TITLE
Rename project

### ISSUE THREAD

**Issue by JoeZwet** [teamgalacticraft/Galacticraft-Fabric#10]
The current project name generic and boring.

**Comment by marcus8448** [comment]
We probably should do this before 1.0.0

**Comment by marcus8448** [comment]
List of things I got from the discord:

- Galacticraft: Rewebbed
- Galacticraft: Tailored Skies
- Galacticraft: Reconstructed
- Galacticraft: Blanket Edition
- Galacticloth
- Galactic Fabrication
- Galacticraft: Fabrication
- Galacticraft: Refabricated
- Galacticraft: Rewrapped
- Galacticraft: Rewoven
- Stringed void
- Webbed horizons
- Galacticraft: Restrung

**Comment by craftablescience** [comment]
I think that we can close this now
