### ISSUE TITLE
Probably not the right place

### ISSUE THREAD

**Issue by SebaSphere** [teamgalacticraft/Galacticraft-Fabric#14]
Can you give acsess for me to edit the github. I would like to make some suggestions and stuff like that. School blocks discord so I gotta use github lmao

@vos6434 @JoeZwet

**Comment by pythonprogrammr2-alt** [comment]
Can't you just make a pull request?

**Comment by pythonprogrammr2-alt** [comment]
btw this is weetlee

**Comment by SebaSphere** [comment]
@pythonprogrammr2-alt I don’t use github that much tbh lol. Really all I’ve used it for is to report issues.

**Comment by craftablescience** [comment]
Hey this is my actual account
Yeah, you can still modify it that way from what I know, I haven't much used the collaborative side of GitHub

**Comment by SebaSphere** [comment]
https://github.com/teamgalacticraft/Galacticraft-Fabric/projects/3

Wanna add some stuff to here

**Comment by craftablescience** [comment]
Fair point, I thought you meant something code related

**Comment by SebaSphere** [comment]
Kek

**Comment by SebaSphere** [comment]
I should probally see if I can draw some textures tho

**Comment by craftablescience** [comment]
Aren't they porting all the original textures over?

**Comment by SebaSphere** [comment]
@JoeZwet @vos6434 @micdoodle8 , Should the wiki be on github or as is? I can probably write stuff on the wiki and help keep things updated.

**Comment by SebaSphere** [comment]
@craftablescience ye they are. I mean any future textures.

**Comment by craftablescience** [comment]
And we should close this issue once the discussion here is over, this is the spot to report code bugs not access bugs lol

**Comment by SebaSphere** [comment]
Lmao does GitHub have any sort of chat function @craftablescience ?

**Comment by craftablescience** [comment]
Yep, but I don't remember how to access it / where it is

**Comment by SebaSphere** [comment]
Oof

**Comment by craftablescience** [comment]
Nvm, was thinking of something else. GitHub doesn't natively support chat, your best bet is Discord

**Comment by SebaSphere** [comment]
F in chat guess I only can communicate through issues at school

**Comment by vos6434** [comment]
Check your notifications.
